id: A0849BE38
base_file: f6C6A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.827268
  last_modified_at: 2022-06-17 11:28:05.827271
