id: A0849BE38
base_file: f78A3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.830945
  last_modified_at: 2022-06-17 11:28:05.830948
