id: A0849BE38
base_file: f7284.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.829475
  last_modified_at: 2022-06-17 11:28:05.829478
