id: A0849BE38
base_file: f0A7B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.822081
  last_modified_at: 2022-06-17 11:28:05.822088
