id: A0849BE38
base_file: f9005.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.832717
  last_modified_at: 2022-06-17 11:28:05.832720
