id: A0849BE38
base_file: f22E8.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:28:05.825707
  last_modified_at: 2022-06-17 11:28:05.825712
